### ISSUE TITLE
Run TXPipe on Fourier space using HSC data.

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/txpipe-reanalysis#17]
Test whether TXPipe runs using the HSC data in Fourier space or not.

More pointers to come.

**Comment by fjaviersanchez** [comment]
* Use the metacal mocked files here: `/global/cfs/cdirs/lsst/groups/LSS/HSC_data` using TXPipe's `2.2i` branch (see [here](https://github.com/LSSTDESC/TXPipe/pull/93)) and try to run the different stages up to getting 2-point data vector and covariance in harmonic space.

* Identify which problems arise (if any).
* If problems arise, document in new issues.
* If pipeline succeeds, compare with @anicola 's results.

**Comment by fjaviersanchez** [comment]
Update: I ran with the master branch as of today and I got to `TXTwoPointFourier`. I found some problems but most of them were easy to fix:

- There are a couple of places where it assumes that all the columns in `data` have the same length and it's not the case for my catalog. e.g:

```
Error in TXDiagnosticPlots: Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/global/u2/j/jsanch87/TXPipe/txpipe/__main__.py", line 5, in <module>
    PipelineStage.main()
  File "/usr/local/lib/python3.6/dist-packages/ceci/stage.py", line 258, in main
    stage.execute(args)
  File "/usr/local/lib/python3.6/dist-packages/ceci/stage.py", line 321, in execute
    stage.run()
  File "/global/u2/j/jsanch87/TXPipe/txpipe/diagnostics.py", line 105, in run
    plotter.send(data)
  File "/global/u2/j/jsanch87/TXPipe/txpipe/diagnostics.py", line 648, in plot_mag_histograms
    w &= (data['source_bin']>=0)
ValueError: operands could not be broadcast together with shapes (13947,) (100000,) (13947,) 
```

- Some residual metacal things in TwoPointFourier e.g.:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/global/u2/j/jsanch87/TXPipe/txpipe/__main__.py", line 5, in <module>
    PipelineStage.main()
  File "/usr/local/lib/python3.6/dist-packages/ceci/stage.py", line 258, in main
    stage.execute(args)
  File "/usr/local/lib/python3.6/dist-packages/ceci/stage.py", line 321, in execute
    stage.run()
  File "/global/u2/j/jsanch87/TXPipe/txpipe/twopoint_fourier.py", line 97, in run
    tomo_info = self.load_tomographic_quantities(nbin_source, nbin_lens, f_sky)
  File "/global/u2/j/jsanch87/TXPipe/txpipe/twopoint_fourier.py", line 526, in load_tomographic_quantities
    mean_R = metadata['tracers/R_gamma_mean'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'R_gamma_mean' doesn't exist)"
```

I'm working on fixing these things (they are probably related to the catalog rather than TXPipe)

**Comment by fjaviersanchez** [comment]
@iltomo is interested :)

**Comment by fjaviersanchez** [comment]
@felipeaoli
